/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesmanager.components.datepicker;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author Lorenzo
 */
public class DatePicker extends javax.swing.JPanel {

    private GregorianCalendar gc;
    /**
     * Creates new form DatePicker
     */
    public DatePicker() {
        initComponents();
        gc = new GregorianCalendar();
        updateDate();
    }
    
    private void updateDate(){
        txtDay.setText(String.format("%02d",gc.get(Calendar.DAY_OF_MONTH)));
        txtMonth.setText(String.format("%02d",gc.get(Calendar.MONTH)+1));
        txtYear.setText(gc.get(Calendar.YEAR) + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDayPlus = new javax.swing.JButton();
        btnMonthPlus = new javax.swing.JButton();
        btnYearPlus = new javax.swing.JButton();
        txtDay = new javax.swing.JTextField();
        txtMonth = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        btnDayLess = new javax.swing.JButton();
        btnMonthLess = new javax.swing.JButton();
        btnYearLess = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Giorno");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel1, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mese");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel2, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Anno");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel3, gridBagConstraints);

        btnDayPlus.setText("+");
        btnDayPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDayPlusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnDayPlus, gridBagConstraints);

        btnMonthPlus.setText("+");
        btnMonthPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthPlusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnMonthPlus, gridBagConstraints);

        btnYearPlus.setText("+");
        btnYearPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYearPlusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnYearPlus, gridBagConstraints);

        txtDay.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtDay, gridBagConstraints);

        txtMonth.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtMonth, gridBagConstraints);

        txtYear.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtYear, gridBagConstraints);

        btnDayLess.setText("-");
        btnDayLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDayLessActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnDayLess, gridBagConstraints);

        btnMonthLess.setText("-");
        btnMonthLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthLessActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnMonthLess, gridBagConstraints);

        btnYearLess.setText("-");
        btnYearLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYearLessActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnYearLess, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnYearPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYearPlusActionPerformed
        gc.add(Calendar.YEAR, 1);
        updateDate();
    }//GEN-LAST:event_btnYearPlusActionPerformed

    private void btnDayPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDayPlusActionPerformed
        gc.add(Calendar.DAY_OF_MONTH, 1);
        updateDate();
    }//GEN-LAST:event_btnDayPlusActionPerformed

    private void btnMonthPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthPlusActionPerformed
        gc.add(Calendar.MONTH, 1);
        updateDate();
    }//GEN-LAST:event_btnMonthPlusActionPerformed

    private void btnDayLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDayLessActionPerformed
        gc.add(Calendar.DAY_OF_MONTH, -1);
        updateDate();
    }//GEN-LAST:event_btnDayLessActionPerformed

    private void btnMonthLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthLessActionPerformed
        gc.add(Calendar.MONTH, -1);
        updateDate();
    }//GEN-LAST:event_btnMonthLessActionPerformed

    private void btnYearLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYearLessActionPerformed
        gc.add(Calendar.YEAR, -1);
        updateDate();
    }//GEN-LAST:event_btnYearLessActionPerformed

    public Date getDate(){
        return gc.getTime();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDayLess;
    private javax.swing.JButton btnDayPlus;
    private javax.swing.JButton btnMonthLess;
    private javax.swing.JButton btnMonthPlus;
    private javax.swing.JButton btnYearLess;
    private javax.swing.JButton btnYearPlus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
