/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package salesmanager.graphics.dialogs.internal;

import java.util.Date;
import salesmanager.beans.Customer;

/**
 *
 * @author Lorenzo
 */
public class CustomerInternalPanel extends BeanPanel {

    /**
     * Creates new form CustomerPanel
     */
    private Customer customer;

    public CustomerInternalPanel() {
        initComponents();
        this.customer = null;
    }

    public void setCustomer(Customer c) {
        if (c != null) {
            txtName.setText(c.getName());
            txtSurname.setText(c.getSurname());
            txtAddress.setText(c.getAddress());
            txtTelephone.setText(c.getTelephone());
            txtCF.setText(c.getCf());
            txtPiva.setText(c.getPiva());
            txtDocID.setText(c.getDocument());
            txtDocRelease.setValue(c.getDocumentRelease());
            txtDocExpiration.setValue(c.getDocumentExpiration());
            txtEntity.setText(c.getDocumentEntity());
            txtCAP.setText(c.getCAP());
            txtCity.setText(c.getCity());
            txtDistrict.setText(c.getDistrict());
            this.customer = new Customer(c);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPiva = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCAP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDistrict = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDocID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDocRelease = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDocExpiration = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEntity = new javax.swing.JTextField();

        setLayout(new java.awt.GridLayout(0, 2, 10, 10));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nome");
        jLabel1.setToolTipText("");
        add(jLabel1);

        txtName.setColumns(15);
        add(txtName);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cognome");
        add(jLabel2);

        txtSurname.setColumns(15);
        add(txtSurname);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Codice fiscale");
        add(jLabel5);

        txtCF.setColumns(15);
        add(txtCF);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("P. IVA");
        add(jLabel13);
        add(txtPiva);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Telefono");
        add(jLabel3);

        txtTelephone.setColumns(15);
        add(txtTelephone);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Indirizzo");
        add(jLabel6);

        txtAddress.setColumns(15);
        add(txtAddress);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("CAP");
        add(jLabel7);
        add(txtCAP);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Città");
        add(jLabel8);
        add(txtCity);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Provincia");
        add(jLabel9);
        add(txtDistrict);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("ID Documento");
        add(jLabel4);

        txtDocID.setColumns(15);
        add(txtDocID);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Data rilascio documento");
        add(jLabel12);

        txtDocRelease.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtDocRelease.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        add(txtDocRelease);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Data scadenza documento");
        add(jLabel11);

        txtDocExpiration.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtDocExpiration.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        add(txtDocExpiration);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Ente");
        add(jLabel10);
        add(txtEntity);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCAP;
    private javax.swing.JTextField txtCF;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDistrict;
    private javax.swing.JFormattedTextField txtDocExpiration;
    private javax.swing.JTextField txtDocID;
    private javax.swing.JFormattedTextField txtDocRelease;
    private javax.swing.JTextField txtEntity;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPiva;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean updateData() {
        String name = txtName.getText();
        String surname = txtSurname.getText();
        String telephone = txtTelephone.getText();
        String address = txtAddress.getText();
        String cf = txtCF.getText();
        String piva = txtPiva.getText();
        String documentID = txtDocID.getText();
        String documentEntity = txtEntity.getText();
        Date documentRelease = (Date) txtDocRelease.getValue();
        Date documentExpiration = (Date) txtDocExpiration.getValue();
        String CAP = txtCAP.getText();
        String city = txtCity.getText();
        String district = txtDistrict.getText();
        if(name == null || name.isEmpty()){
            return false;
        }
        Customer updated = new Customer(name, surname,cf,piva, telephone, address, documentID,documentRelease,documentExpiration,documentEntity, CAP, city, district);
        if (customer != null) {
            updated.setCode(customer.getCode());
            this.customer = updated;
        } else {
            this.customer = updated;
        }
        return true;
    }

    public Customer getCustomer() {
        return customer;
    }
}
