/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesmanager.graphics;

import java.util.GregorianCalendar;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author naigo
 */
public class InvoicesAdjusterFrame extends javax.swing.JFrame {

    /**
     * Creates new form InvoicesAdjusterFrame
     */
    public InvoicesAdjusterFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnEmptyInvoices = new javax.swing.JButton();
        btnProgressives = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnEmptyInvoices.setText("Rimozione fatture vuote");
        btnEmptyInvoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmptyInvoicesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnEmptyInvoices, gridBagConstraints);

        btnProgressives.setText("Compattamento progressivi");
        btnProgressives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProgressivesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnProgressives, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Anno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtYear.setText(Integer.toString(new GregorianCalendar().get(Calendar.YEAR) - 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtYear, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmptyInvoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmptyInvoicesActionPerformed
        try {
            InvoicesAdjuster adjuster = new InvoicesAdjuster();
            List<Integer> codes = adjuster.getEmpty(Integer.parseInt(txtYear.getText()));
            if (codes.size() > 0) {
                if (JOptionPane.showConfirmDialog(this, "Ci sono " + codes.size() + " fatture vuote: " + printIntList(codes) + " Rimuovere?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    adjuster.remove(codes);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tutto ok!");
            }
        } catch (Exception ex) {
            Logger.getLogger(InvoicesAdjusterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEmptyInvoicesActionPerformed

    private void btnProgressivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgressivesActionPerformed
        try {
            InvoicesAdjuster adjuster = new InvoicesAdjuster();
            boolean needToBeAdjusted = adjuster.hasHoles(Integer.parseInt(txtYear.getText()));
            if (needToBeAdjusted) {
                if (JOptionPane.showConfirmDialog(this, "Ci sono dei buchi: Aggiustare?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    adjuster.compact(Integer.parseInt(txtYear.getText()));
                    JOptionPane.showMessageDialog(this, "Fatto!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tutto ok!");
            }
        } catch (Exception ex) {
            Logger.getLogger(InvoicesAdjusterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProgressivesActionPerformed

    private String printIntList(List<Integer> list) {
        return list.stream().reduce("",
                (str, number) -> {
                    if (!str.isEmpty()) {
                        return str + ", " + number;
                    }
                    return Integer.toString(number);
                },
                (str1, str2) -> {
                    if (!str1.isEmpty()) {
                        return str1 + ", " + str2;
                    }
                    return str1 + str2;
                });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoicesAdjusterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoicesAdjusterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoicesAdjusterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoicesAdjusterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoicesAdjusterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmptyInvoices;
    private javax.swing.JButton btnProgressives;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
