/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesmanager.components;

/**
 *
 * @author naigo
 */
public class NavigatorPanel extends javax.swing.JPanel {

    /**
     * Creates new form NavigatorPanel
     */
    private int current;
    private int pages;

    public NavigatorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnBackward = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnForward = new javax.swing.JButton();
        lblCurrent = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTot = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        btnBackward.setText("Indietro");
        btnBackward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackwardActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnBackward, gridBagConstraints);

        jLabel1.setText("pag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel1, gridBagConstraints);

        btnForward.setText("Avanti");
        btnForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForwardActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnForward, gridBagConstraints);

        lblCurrent.setText(".");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblCurrent, gridBagConstraints);

        jLabel3.setText("di");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel3, gridBagConstraints);

        lblTot.setText(".");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblTot, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public void setPages(int pages) {
        this.pages = pages;
        this.current = 0;
        updateView();
    }
    
    public int getCurrentPage(){
        return current;
    }
    
    private void btnBackwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackwardActionPerformed
        if (current > 0) {
            current--;
            firePropertyChange("page", current + 1, current);
        }
        updateView();
    }//GEN-LAST:event_btnBackwardActionPerformed

    private void btnForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForwardActionPerformed
        if (current < pages - 1) {
            current++;
            firePropertyChange("page", current - 1, current);
        }
        updateView();
    }//GEN-LAST:event_btnForwardActionPerformed

    private void updateView(){
        btnBackward.setEnabled(current > 0);
        btnForward.setEnabled(current < pages - 1);
        lblCurrent.setText(String.valueOf(current + 1));
        lblTot.setText(String.valueOf(pages));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackward;
    private javax.swing.JButton btnForward;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCurrent;
    private javax.swing.JLabel lblTot;
    // End of variables declaration//GEN-END:variables
}
